[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

autoload -Uz compinit
typeset -i updated_at=$(date +'%j' -r ~/.zcompdump 2>/dev/null || stat -f '%Sm' -t '%j' ~/.zcompdump 2>/dev/null)
if [ $(date +'%j') != $updated_at ]; then
    compinit -i
else
    compinit -C -i
fi
zmodload -i zsh/complist

# Aliases
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias grep='grep --color=auto'
alias less='less -R'

OS="$(uname)"
if [[ "$OS" == "Linux" ]]; then
    alias bat='batcat --theme base16 -p'
    alias ls='ls -h --color=auto'
    alias la='ls -lah --color=auto'
fi

# Exports
export TERM="xterm-256color"
export LANGUAGE="C.UTF-8"
export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
export LC_CTYPE="C.UTF-8"
export LC_MESSAGES="C.UTF-8"
# sources
source $HOME/.zsh/powerlevel10k/powerlevel10k.zsh-theme
source $HOME/.zsh/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
source $HOME/.zsh/completion.zsh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
source $HOME/.zsh/history.zsh
source $HOME/.zsh/key-bindings.zsh
source /home/nicola/Distrobox/debian-test/.zsh/z.plugin.zsh
source /home/nicola/Distrobox/debian-test/.zsh/sudo.plugin.zsh

    HIST_STAMPS="%Y-%m-%d %T "

    ##FUNZIONI

    # CHEATSHEET RAPIDA CMD
    function cheat {
            curl cht.sh/$1
    }
    # mkdir and cd into it
    mcd() { mkdir -p "$1"; cd "$1";}

    # PERSONAL ALIAS
    # fast shut & reboot
    alias shut="sudo shutdown now"
    alias reboot="sudo reboot now"
    #alias ls="exa --icons"
    # temp dir
    alias tmpd="cd $(mktemp -d)"
    # alias batcat
    alias cat="batcat"
    # nala
    alias nala="sudo nala"
    # fdfind
    alias fd="fdfind"
    # empty trash
    alias et="rm -rf  ~/.local/share/Trash/* "
    #Pbcopy/Pbpaste
    alias pbcopy="xsel --input --clipboard"
    alias pbpaste="xsel --output --clipboard"
    
    #nvim path  
    export PATH="$PATH:/opt/nvim/"

